version: 2.0
sudo: required
services:
  - docker

before_install:
  - docker build -t sandipdhakal9/docker-react -f Dockerfile.dev .

script:
  - docker run sandipdhakal9/docker-react npm run test -- --coverage
